### ISSUE TITLE
Tutorial is confusing

### ISSUE THREAD

**Issue by shendriksza** [commercelayer/gatsby-commerce#1]
Apologies for opening an issue for this, but I'm struggling to understand how I am supposed to use this gatsby plugin. How do I query products and prices from Commerce Layer to dynamically build product pages? Do I have to implement the REST calls myself?

**Comment by fconforti** [comment]
@shendriksza to better understand how it works, take a look at the following tutorial:

https://github.com/commercelayer/static-commerce

The Gatsby plugin just make it easier to implement the tutorial above on a Gatbsy project, by including some ready-to-use react components:

https://github.com/commercelayer/commercelayer-react)

and the JS Library itself:

https://github.com/commercelayer/commercelayer-js

Please keep in mind that Commerce Layer manages SKUs, prices, stock information, and all the resources you need to add ecommerce to any content. The product page information, including custom attributes and categories should be managed through a headless CMS.

The blog post below on the Contentful blog should help you clarify even better how it works:

https://www.contentful.com/blog/2018/11/07/how-build-static-site-ecommerce-jekyll-contentful-commerce-layer/

F.

**Comment by shendriksza** [comment]
Excellent blog post. Thank you so much for reaching out I appreciate it greatly.
I have a much better understanding of commerce-layer's role in the architecture now.

**Comment by fconforti** [comment]
Great! Just let me know if you have any other questions.

Thanks,
F.
