### ISSUE TITLE
Problems with offline mode

### ISSUE THREAD

**Issue by jusnak3** [commercelayer/gatsby-commerce#3]
I have problem with using this plugin together with [gatsby-plugin-offline](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline).

What I did:
```
gatsby new gatsby-commerce
npm install gatsby-plugin-commercelayer --save
```

```
# gatsby-config.js
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    `gatsby-plugin-offline`,
	`gatsby-plugin-commercelayer`
  ],
}
```

Also, I added **<CLayer.Config** to **layout.js** and **<CLayer.Price skuCode="code here"/>** to **index.js**.
It works good while I open the app (after **build** & **serve**) and while I'm going from main page to default page-2 - it works fine. But if refresh home page - no price will load anymore until cache cleared.

Here is the console error:
```
commercelayer.min.js:1 Uncaught TypeError: Cannot read property 'dataset' of null
    at Object.<anonymous> (commercelayer.min.js:1)
    at n (commercelayer.min.js:1)
    at Object.<anonymous> (commercelayer.min.js:1)
    at n (commercelayer.min.js:1)
    at r (commercelayer.min.js:1)
    at HTMLDocument.<anonymous> (commercelayer.min.js:1)
```

UPD: as I can see after page cached - there is no Clayer config DOM element presented.

**Comment by acasazza** [comment]
Hi @jusnak3, thanks! I replicated the bug, and I will resolve it asap! 😉

**Comment by jusnak3** [comment]
@acasazza, thank you for fast reaction!

**Comment by jusnak3** [comment]
@acasazza, hi there, do you have any updates? When do you plan to fix that?

**Comment by acasazza** [comment]
Hi @jusnak3, sorry for the delay.
I fixed the bug, but unfortunately, I found another. 😞 The reason is the service worker and gatsby because now, we import the library as an external script. Also, for this, we made the new react components, and we will release them at the end of the month. I think that it will be the best way for you.
